---
title: "Моделирование распределений"
output:
    pdf_document:
        extra_dependencies:
            inputenc: ["utf8"]
            babel: ["russian"]

---




```{r, include=FALSE}
knitr::opts_chunk$set(fig.width = 6, fig.height = 4)
library(ggplot2)
```

```{r, include=FALSE}
c <- 2 * exp(6) / (5 * exp(6) + 1)
p_ <- function(x) {
    if (x < 0) return(-x * exp(-x^2))
    else if (x < 2) return(1)
    else if (x < 3) return(0)
    else return(exp(-2 * x))
}
p <- function(x) c * p_(x)
theory_distribution <- data.frame(value = seq(-5, 5, by = 0.1))
theory_distribution$dens <- sapply(theory_distribution$value, FUN = p)
```

# Метод обратной функции

Когда я переносил обратные функции в алгоритм я перепутал $\frac{2}{c}$ и $\frac{c}{2}$. Если это исправить, то результат такой:
```{r}
reverse_method <- function() {
    c <- 2 * exp(6) / (5 * exp(6) + 1)
    alpha <- runif(1)
    a <- c / 2
    b <- 5 * c / 2
    if (alpha < a) return(-sqrt(-log(1/a * alpha)))
    else if (alpha < b) return(alpha / c - 1 / 2)
    else return(-1 / 2 * log(1/a * (1 - alpha)))
}
sample <- data.frame(value = replicate(100000, reverse_method()))
ggplot() +
    geom_histogram(data = sample, aes(x = value, y = ..density..), binwidth = 0.1) +
    geom_line(data = theory_distribution, aes(x = value, y = dens)) +
    labs(title = "Reverse Method") + xlim(-5, 5)
    
```
\newpage

# Метод декомпозиции

```{r}
decompose_method <- function() {
    c <- 2 * exp(6) / (5 * exp(6) + 1)
    alpha1 <- runif(1)
    alpha2 <- runif(1)
    if (alpha1 < c / 2) return(-sqrt(-log(alpha2)))
    else if (alpha1 < 5 * c / 2) return(2 * alpha2)
    else return((c - log(1 - alpha2)) / 2)
}
sample <- data.frame(value = replicate(100000, decompose_method()))
ggplot() +
    geom_histogram(data = sample, aes(x = value, y = ..density..), binwidth = 0.1) +
    geom_line(data = theory_distribution, aes(x = value, y = dens)) +
    labs(title = "Decompose Method") + xlim(-5, 5)
```
\newpage

# Метод отбора

тут одна скобка не там стояла в генерации nu
```{r}
selection_method <- function() {
    c <- 2 * exp(6) / (5 * exp(6) + 1)
    repeat{
        alpha1 <- runif(1)
        alpha2 <- runif(1)
        if (alpha1 < 1 / 2) nu <- log(2 * alpha1) + 1
        else nu <- 1 - log(2 * (1 - alpha1))

        if (nu < 0) r <- -nu * exp(-nu^2 - nu + 1)
        else if (nu < 1) r <- exp(1 - nu)
        else if (nu < 2) r <- exp(nu - 1)
        else if (nu < 3) r <- 0
        else r <- exp(-2 * nu + nu - 1)

        if (r > exp(1) * alpha2) break
    }
    return(nu)
}
sample <- data.frame(value = replicate(100000, selection_method()))
ggplot() +
    geom_histogram(data = sample, aes(x = value, y = ..density..), binwidth = 0.1) +
    geom_line(data = theory_distribution, aes(x = value, y = dens)) +
    labs(title = "Selection Method") + xlim(-5, 5)
```
